name: agile
recipe: drupal8
config:
  webroot: docroot
  # ==========================
  # Prevent errors
  # @see https://github.com/lando/lando/issues/908#issue-316416561
  # ==========================
  database: 'mysql:5.7'
  # ==========================
  # Enable XDebug
  # @see https://gist.github.com/MatthieuScarset/0c3860def9ff1f0b84e32f618c740655 
  # ==========================
  #xdebug: true
  #conf: 
  #  php: .vscode/php.ini
services:
  node:
    type: node:6.10
    build:
      - echo "Installation completed!"
tooling:
  npm:
    service: node      
events:
  post-start:
    #########################################################
    # DAILY UPDATE - Keep your codebase up to date.
    #########################################################
    - echo "Installing dependencies..."
    - appserver: "cd $LANDO_MOUNT/ && composer install --no-interaction --optimize-autoloader"
    #
    #########################################################
    # FIRST INSTALL - Remove those lines after first install.
    # Drupal automatic install with config_installer profile.
    # @see docroot/sites/default/settings.php
    # @see docroot/sites/default/settings.local.php
    # @see scripts/composer/ScriptHandler::siteInstall()
    # @see scripts/composer/ScriptHandler::siteUser()
    #########################################################
    - echo "First install"
    - appserver: "cd $LANDO_MOUNT/ && composer first-install"
    - echo "Building theme assets..."
    #
    #########################################################
    # DAILY UPDATE - To be run everyday after lando start.
    #########################################################
    #- echo "Updating database..."
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush cim -r docroot"
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush entup -r docroot"
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush updb -r docroot"
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush locale-update -r docroot"
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush cr -r docroot"
    - echo "Building theme assets..."
    - node: "cd $LANDO_MOUNT && npm run reset"
    - appserver: "cd $LANDO_MOUNT/ && ./bin/drush cr -r docroot"    
    #
    #########################################################
    # TESTING - The most important thing in the world.
    #########################################################
    #- echo "Checking coding standards..."
    #- node: "cd $LANDO_MOUNT && npm run lint"
    #- appserver: "cd $LANDO_MOUNT/ && composer code-review"
    #- echo "SonarQubing..."
    #- echo "PHPUniting..."
    #
    #########################################################
    # Just for fun :)
    #########################################################
    #- echo "Calculating statistics..."
    #- node: "cd $LANDO_MOUNT && npm run stats"    
